### ISSUE TITLE
ServiceConfigurationError when in a modular project

### ISSUE THREAD

**Issue by fwgreen** [pgjdbc/pgadba#29]
I'm able to connect and retrieve data, but once I add a `module-info.java` to my project I get this error at runtime...
```
java.util.ServiceConfigurationError: jdk.incubator.sql2.DataSourceFactory: module org.postgresql.adba does not declare `uses`
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:590)
        at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:576)
        at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:505)
        at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1692)
        at org.postgresql.adba/jdk.incubator.sql2.DataSourceFactory.newFactory(DataSourceFactory.java:52)
...
```
Adding `uses jdk.incubator.sql2.DataSourceFactory` doesn't change the output.
```Java
module main {
	requires org.postgresql.adba;
	//uses jdk.incubator.sql2.DataSourceFactory;
}
```

**Comment by alexanderkjall** [comment]
I tried to reproduce the error without success here: https://github.com/alexanderkjall/pgadba-example-application-spring-boot/tree/module-path-example

Could you show a way to reproduce it?

**Comment by fwgreen** [comment]
My project is a basic `Hello World` with only one dependency.  Here is my pom.xml
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.fwgreen</groupId>
	<artifactId>PostgresTest</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>pgadba</artifactId>
			<version>0.1.0-ALPHA</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<release>11</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```
I suspect Spring might be using some trickery to smooth out the rough edges of the module system.

**Comment by alexanderkjall** [comment]
Thanks for reporting the bug.
