### ISSUE TITLE
rowCountOperation("SELECT …") fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mp911de** [pgjdbc/pgadba#31]
Executing a `SELECT` query fails with `ArrayIndexOutOfBoundsException` when invoked through `rowCountOperation(…)`. The exception is not propagated to the result, it just appears via syserr.

Note: Select queries are not really intended for row counts but this bug crossed my path so I wanted to report it.

Postgres version: PostgreSQL 10.4 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit

Reproducer:

```java
    private DataSource dataSource() {

        return DataSourceFactory.newFactory("org.postgresql.adba.PgDataSourceFactory")
                .builder()
                .url("jdbc:postgresql://localhost:5432/postgres")
                .username("postgres")
                .password("")
                .build();
    }

    @Test
    public void shouldCount() {

        DataSource ds = dataSource();

        CompletableFuture<Long> t;
        try (Session session = ds.getSession()) {

            Submission<Long> count = session
                    .<Long>rowCountOperation("SELECT * FROM pg_tables")
                    .apply(it -> it.getCount()).submit();

            t = count.getCompletionStage().toCompletableFuture();
        }

        t.join();

        assertThat(t.join()).isNotNull();

        ds.close();
    }
```

```
java.lang.ArrayIndexOutOfBoundsException: Index -16777165 out of bounds for length 68
	at org.postgresql.adba.communication.packets.DataRow.<init>(DataRow.java:34)
	at org.postgresql.adba.communication.network.ExecuteResponse.read(ExecuteResponse.java:29)
	at org.postgresql.adba.communication.NetworkConnection.handleRead(NetworkConnection.java:394)
	at org.postgresql.adba.execution.DefaultNioLoop.run(DefaultNioLoop.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by alexanderkjall** [comment]
Thanks for the bug report, there needs to be a nice error propagated to the end user here.
