### ISSUE TITLE
When an exception occurs, the connection cannot be recycled

### ISSUE THREAD

**Issue by zhangtianxiao** [pgjdbc/pgadba#39]
```java
Caused by: pgnio.DriverException$NoConversion: No conversion defined for class [Ljava.lang.Object;
	at pgnio.ParamWriter.write(ParamWriter.java:75)
	at pgnio.ParamWriter.write(ParamWriter.java:63)
	at pgnio.QueryBuildConnection$Prepared.sendBindWithConvertedParams(QueryBuildConnection.java:146)
```

then, when id call `ds.returnConnection`, will happen

```java
java.lang.IllegalStateException: Length already started
	at pgnio.BufWriter$Simple.writeLengthIntBegin(BufWriter.java:101)
	at pgnio.QueryBuildConnection.sendSync(QueryBuildConnection.java:57)
	at pgnio.QueryBuildConnection.done(QueryBuildConnection.java:71)
	at pgnio.QueryBuildConnection.reset(QueryBuildConnection.java:66)
	at pgnio.Connection$Started.fullReset(Connection.java:438)
	at pgnio.Connection$Started.fullReset(Connection.java:438)
	at pgnio.ConnectionPool.returnConnection(ConnectionPool.java:139)
```

**Comment by davecramer** [comment]
This project is pretty much dead. Not sure you are going to get a response here.

**Comment by cretz** [comment]
@zhangtianxiao - Looks like your question may be for https://github.com/cretz/pgnio which, while not "dead", I also don't actively work on. Might want to ask there, though be advised I may not be able to look in detail.
